plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap

theme: jekyll-theme-modernist
    
url           : "https://infominer.id/DIDecentralized"
baseurl       : "/DIDecentralized"
title         : Digital Identity Decentralized
description   : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
author        : "⧉ Infominer"
logo          : "https://infominer.id/images/crypt0library.png"
repository    : "infominer33/DIDecentralized"
github        : [metadata]


twitter:
  site        : "infominer33"
  title       : Digital Identity Decentralized
  description : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
  image       : "https://infominer.id/images/og-image.jpg"
  card        : "summary"
 
google_analytics: UA-132558656-1