plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap
    
url           : "https://infominer.id/DIDecentralized"
baseurl       : "/DIDecentralized"
title         : Digital Identity Decentralized — DID
description   : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
author        : "⧉ Infominer"
logo          : "https://infominer.id/images/crypt0library.png"
repository    : "infominer33/DIDecentralized"
github        : [metadata]

theme: jekyll-theme-modernist

twitter:
  title       : Decentralized Identity — DID
  site        : "infominer33"
  description : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
  card        : "summary"
og_image       : "https://infominer.id/images/og-image.jpg"
 
google_analytics: UA-132558656-1