# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Decentralized ID - Curated"
title_separator          : "| "
name                     : "Infominer"
description              : "Learning to create an Identity Layer for the Internet, that is vendor agnostic and as widely interoperable, as possible, putting users in control of their personal information."
url                      : "https://decentralized-id.com"
baseurl                  : ""
repository               : "Decentralized-ID/decentralized-id.github.io"
github                   : [metadata]
teaser                   : /images/didecentral-tw.png
logo                     : "https://decentralized-id.com/images/DID.png"
masthead_title           : "Digital Identity Decentralized"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2"
staticman:
  allowedFields          : ["name", "email", "url", "message"]
  repository             : Decentralized-ID/decentralized-id.github.io 
  branch                 : "master"
  commitMessage          : "New comment by {fields.name}"
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ["name", "message"]
  generatedFields:
    date:
      type: "date"
      options:
        format: "timestamp-seconds" #"timestamp-milliseconds"
  endpoint               : https://identosphere.net/staticman/v2/entry/

reCaptcha:
  siteKey: 6LfHeawUAAAAAATc0Sckhl9FJLGog3m7qLrYA8V0
  secret               : jG+tpXA7GdYSuIT/rcr5pyy9GG/ZP6808NE8SS+/ggGZ0Si0/uelJpZuElRrIITjfB7YjW6+MyWEBM/q/BFWQqRfkpCZ0RK5AETrx/awrvKSlCVCQfpN20MFpu54yFgkyj82umuoxOyiVczwUnkD8Sav0cXESbllHgC+2J2hw6nOYQ+ZnOFL4J4m3yoABhyGpKnhzw7enmaAm+pbxPXyLhjj9+LiRqGLWNUYOt+yOuo/i1aeE8p0lYwdESVoetkuNfKf1Q13Vs/KSPGceVXWLJAf7mDlwCf8wGrAZzCGAd9GQJM3KjliB+0hGOWs9X01+PdUr6ZeeGrAFjBERZXpTPdJmHDBmUNnX5Tdvhq9uU4I3NcZveIg5FyjLe4nMG30ha/hALW4KLvspzCL8nYWpFl27RTqN6v735xcBgcfVR4JPfInb91/EtAFe3gyM3BCe3enuiezGDZsqCn+glQZ7adeOrCaZ0pLG+FmL7WXR2QsSfq70biUp6uLZtGfJ4W9I9DIezbj3Z/ltJRFVTmWHGp3g4/2LAcsDLMfyR4QLVkcgqQjuAbYk3ItPNuLPAVV6mbHKvBmyoyimT1SpPWgu6uJCRkCyU90DMsBK/xNzhep9ljp73qV2B3qHvFqHIKKzYEoA2rtQexTsRWxf+20axauwWO/DdpcOqOQC8mUqBE=

atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_provider          : algolia #  lunr (default), algolia, google
algolia:
  application_id         : Q7H7K9X8DV
  index_name             : didecentral
  search_only_api_key    : c02bbc81162fc9aaaf03cd6573962a94 # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :




# Social Sharing
twitter:
  username               : "infominer33"
  site: "didecentral"
#  description            : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
#  image                  : "https://decentralized-id.com/images/IDecentralized.png"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : https://decentralized-id.com/images/didecentral-tw.png
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : custom # false (default), "google", "google-universal", ""
  google:
    tracking_id          : #UA-132558656-3
    anonymize_ip         : true

# Site Author
author:
  name             : "DIDecentral"
  avatar           : /images/did-square.png
  bio              : "Collaborative Curation, Community Research Initiative"
  location         : "Curating the Web"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:identitydecentralized@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://decentralized-id.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Decentralized-ID"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DecentralizeID"
# https://fontawesome.com/icons/telegram?style=brands
# Just go to fontawesome.com and add whatever social sites you need here.


# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:identitydecentralized@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://decentralized-id.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DecentralizeID"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Decentralized-ID"
    
    

# Reading Files
include:
  - .htaccess
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /posts/page:num/
timezone: Pacific/Fakaofo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-mentions


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


collections:
  HowToContribute:
    output: true
    permalink: /how-to-contribute/:path/


# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      header:
        image: /images/digital_geralt-93001_thin.jpg
      sidebar:
        - title: "Identity Decentralized"
          image: "/images/regulation_gdpr_data_protection_TheDigitalArtist.png"
          image_alt: "regulation-gdpr-data-protection-3246979"
          nav: "didnav"
      layout: single
      author_profile: false
      read_time: false
      comments: # true
      share: true
      related: true
      toc: true
      toc_sticky  : true  
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      sidebar:
        - title: "Identity Decentralized"
          image: "/images/regulation_gdpr_data_protection_TheDigitalArtist.png"
          image_alt: "regulation-gdpr-data-protection-3246979"
          nav: "didnav"
      layout: single
      author_profile: false
      header:
        image: /images/digital_geralt-93001_thin.jpg
      read_time: true
      comments: true
      share: true
      classes: wide
      related: true
      toc: true
      toc_label   : "Contents"
      toc_icon    : "link"
      toc_sticky  : true
  # _HowToContribute
  - scope:
      path: "_HowToContribute"
      type: HowToContribute
    values:
      header:
        image: /images/didecentral-tw.png
      layout: single
      share: true
      related: true
      sidebar:
        - title: "Identity Decentralized"
          image: "/images/regulation_gdpr_data_protection_TheDigitalArtist.png"
          nav: "didnav"
      classes: wide
