plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-mentions

jekyll-mentions: https://twitter.com

theme: jekyll-theme-modernist
url           : "https://infominer.id"
baseurl       : "/DIDecentralized"
rooturl       : "https://infominer.id/DIDecentralized"    
title         : "Identity Decentralized"
description   : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
author        : "⧉ Infominer"
logo          : "https://infominer.id/DIDecentralized/images/IDecentralized.png"
repository    : "infominer33/DIDecentralized"
github        : [metadata]
image         : "https://infominer.id/DIDecentralized/images/IDecentralized.png"

twitter:
  site        : "infominer33"
  title       : "Identity Decentralized"
  description : "Resources for Creating a Vendor Agnostic, User-Controlled, Identity Layer for the Internet."
  image       : "https://infominer.id/DIDecentralized/images/identity-decentralized.png"
  card        : "summary"
 
google_analytics: UA-132558656-1

