["Remme Auth"]
Link = ["https://remme.io/","https://github.com/Remmeauth"]
Description = "Using a Hyperledger Sawtooth foundation, Remme implements a DPKI. Its blockchain playing the role of CA and supporting X.509 certificates either signed by the user, or an organization."
Tags = ["blockchain-id","dpki","sawtooth","x-509"]

["Juru"]
Link = ["https://juru.io/","https://github.com/juru-identity/dbh17"]
Description = "Juru Core is an open platform where you can securely store and manage your Identity and Reputation.\n\nToday Juru Core is built on Hyperledger Fabric and BigChainDB, and runs on a permissioned private blockchain. The contributing nodes are hosted by all major banks, which act as reputable gatekeeper.\n\nIt represents your identity and reputation using a smart contract, attributes can be added by the identity owner and are stored in hash form. Attributes and endorsements are formed of field sets, merkle-root hashes are used to allow sharing and verification of partial data"
Tags = ["blockchain-id","hyperledger-fabric","bigchaindb"]

["Shyft Network"]
Link = ["https://www.shyft.network/","https://www.shyft.network/pdfs/Shyft-Network-Inc-Whitepaper_V3.1.pdf"]
Description = "supports the collection of users’ data off-chain using traditional databases and collection strategies with the ability to provide attestation points for third-party utilization."
Tags = ["blockchain-id","kyc"]

["MyEarth"]
Link = ["http://myearth.id/","http://myearth.id/wp-content/uploads/2018/04/Earth-ID-Updated-v1.1.pdf"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://cultu.re/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.iov42.com/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://hu-manity.co/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.zulurepublic.io/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://blocknify.com/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://handshake.org/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://urbit.org/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://vetri.global/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://everid.net/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.agrello.io/"]
Description = ""
Tags = ["",""]

[""]
Link = ["http://gatacaid.com/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.clear.me/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://poa.network/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://essentia.one/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.digidentity.eu/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://lifeid.io/"]
Description = ""
Tags = ["",""]

[""]
Link = ["http://www.usechain.net/"]
Description = ""
Tags = ["",""]

[""]
Link = ["http://ydentity.org/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.digi-id.io/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://0xcert.org/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://github.com/MakoLab/graphchain"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://aid.technology/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://cryptoslate.com/t-mobile-next-identity-platform/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://dock.io/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://herdius.com/"]
Description = ""
Tags = ["",""]

[""]
Link = ["http://ixo.foundation/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.hubtoken.org/"]
Description = ""
Tags = ["",""]

["Holonet"]
Link = [""]
Description = ""
Tags = ["",""]

[""]
Link = ["http://finid.me/"]
Description = ""
Tags = ["",""]

["Crayonic"]
Link = [""]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.blockpass.org/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://www.ledgerstate.io/"]
Description = ""
Tags = ["",""]

[""]
Link = ["https://keeex.me/"]
Description = ""
Tags = ["",""]
